create or replace FUNCTION       GET_CLASSIFICACAO_OPERACAO (
		NUMIDOPERACAO IN NUMBER,
		NUMIF IN NUMBER,
		NUMIDTIPOOPEROBJETOSERV IN NUMBER,
		DATOPERACAO IN DATE,
		QTDOPERACAO IN NUMBER,
		GRUPOECONOMICOPARTE IN VARCHAR,
		GRUPOECONOMICOCONTRAPARTE IN VARCHAR
	) 
	RETURN VARCHAR IS
     RETORNOCLASSIFICACAO VARCHAR2(1);
	BEGIN
		IF GRUPOECONOMICOPARTE = GRUPOECONOMICOCONTRAPARTE
			THEN RETURN 'I';
    END IF;  

    RETORNOCLASSIFICACAO := 'G';

    SELECT 
          CASE
         WHEN EXISTS
          (SELECT 1
							FROM CETIP.OPERACAO OP_REL
							LEFT OUTER JOIN CETIP.V_PARTICIPANTE_GESTOR_GRUPOEC GESTOR_GRUPOEC_PARTE_REL ON (GESTOR_GRUPOEC_PARTE_REL.NUM_CONTA_PARTICIPANTE = OP_REL.NUM_CONTA_PARTICIPANTE_P1)
							LEFT OUTER JOIN CETIP.V_PARTICIPANTE_GESTOR_GRUPOEC GESTOR_GRUPOEC_CONTRAPARTE_REL ON (GESTOR_GRUPOEC_CONTRAPARTE_REL.NUM_CONTA_PARTICIPANTE = OP_REL.NUM_CONTA_PARTICIPANTE_P2)
							JOIN CETIP.TIPO_OPER_OBJETO_SERV TOOS ON (OP_REL.NUM_ID_TIPO_OPER_OBJETO_SERV = TOOS.NUM_ID_TIPO_OPER_OBJETO_SERV)
                            JOIN CETIP.TIPO_OPERACAO TOP ON (TOOS.NUM_ID_TIPO_OPERACAO = TOP.NUM_ID_TIPO_OPERACAO)
                            WHERE NUMIF = OP_REL.NUM_IF
								AND NUMIDTIPOOPEROBJETOSERV = OP_REL.NUM_ID_TIPO_OPER_OBJETO_SERV
								AND ((TOP.COD_TIPO_OPERACAO = 52 AND OP_REL.COD_SITUACAO_OPERACAO = 43) OR (TOP.COD_TIPO_OPERACAO = 552 AND (OP_REL.COD_SITUACAO_OPERACAO = 501 OR OP_REL.COD_SITUACAO_OPERACAO = 227)))
								AND DATOPERACAO = OP_REL.DAT_OPERACAO
								AND QTDOPERACAO = OP_REL.QTD_OPERACAO
								AND GESTOR_GRUPOEC_PARTE_REL.NOME_GRUPO_ECONOMICO = GRUPOECONOMICOCONTRAPARTE
								AND GESTOR_GRUPOEC_CONTRAPARTE_REL.NOME_GRUPO_ECONOMICO = GRUPOECONOMICOPARTE
								AND OP_REL.NUM_ID_OPERACAO != NUMIDOPERACAO) 
            THEN 'I'
         ELSE 'E'
         END 
    INTO RETORNOCLASSIFICACAO 
    FROM DUAL ;

		RETURN RETORNOCLASSIFICACAO;
	END;

