SELECT 'ALTER ' || REPLACE(A.OBJECT_TYPE,' BODY', '') || ' ' || A.OWNER || '.' || A.OBJECT_NAME || ' COMPILE ' || DECODE(A.OBJECT_TYPE, 'PACKAGE BODY', 'BODY')|| ';' AS COMMAND
  FROM DBA_OBJECTS A
 WHERE A.STATUS = 'INVALID'
   AND A.OWNER IN ('CORRWIN','SINAWIN')
 ORDER BY A.OWNER, A.OBJECT_TYPE;