SELECT A.SID,
       A.SERIAL#,
       A.USERNAME,
       A.STATUS,
       A.SCHEMANAME,
       A.OSUSER,
       A.MACHINE,
       A.TERMINAL,
       A.PROGRAM,
       A.MODULE,
       A.LOGON_TIME
  FROM V$SESSION A
 WHERE A.USERNAME NOT IN ('SYS', 'SYSTEM')
ORDER BY A.USERNAME, A.SCHEMANAME, A.STATUS, A.MACHINE, A.TERMINAL, A.OSUSER, A.PROGRAM;



SELECT A.*
  FROM V$SESSION A
 WHERE A.STATUS = 'ACTIVE';
 

SELECT A.*,
       B.object_name
  FROM V$LOCKED_OBJECT A,
       DBA_OBJECTS B
 WHERE A.OBJECT_ID = B.OBJECT_ID;
  

SELECT A.*,
       B.*
  FROM V$LOCK A,
       V$SESSION B
 WHERE A.SID = B.SID;
  

SELECT A.*
  FROM V$LOCK_ACTIVITY A; 