SELECT A.SID, 
       A.SERIAL#, 
       A.USERNAME, 
       A.STATUS, 
       A.SCHEMANAME, 
       A.OSUSER, 
       A.MACHINE, 
       A.TERMINAL, 
       A.PROGRAM, 
       A.MODULE, 
       A.LOGON_TIME, 
       'EXEC DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(SID=>' || A.SID || ', SERIAL#=>' || A.SERIAL# || ', SQL_TRACE=>TRUE);',

       'EXEC DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(SID=>' || A.SID || ', SERIAL#=>' || A.SERIAL# || ', SQL_TRACE=>FALSE);'

  FROM V$SESSION A 
 WHERE UPPER(A.MACHINE) = 'SAOSHASP0025' 
    OR UPPER(A.OSUSER) = 'HIROGUI' 
ORDER BY A.MACHINE, A.OSUSER;
